import { useState } from 'react'
import Attachments from './Attachments'
import { CalendarDays, Check, Clock3, Plus, Repeat2, SlidersHorizontal, Undo2 } from 'lucide-react'
import { api } from '../lib/api'
import type { Bill, Commitment, Commit, Snapshot, Transaction } from '../lib/types'
import { dateLabel, money, moneyDecimal, parseMoney, today } from '../lib/finance'
import { billRemaining, nextMonth } from '../lib/planning'
import { exchange } from '../lib/investments'
import { useCurrency } from '../lib/CurrencyContext'
import AnimatedMoney from '../components/motion/AnimatedMoney'
import { MoneyField, PlanningDialog, PlanningReferences } from './PlanningShared'
import InlineCreate from './InlineCreate'

interface Props { snapshot: Snapshot; projectId: string; onCommit: Commit }
function BillEditor({ snapshot, projectId, bill, template, recurring, onCommit, onClose }: Props & { bill?: Bill; template?: Commitment; recurring?: boolean; onClose: () => void }) {
  const existing = bill || template
  const defaultAccount = snapshot.accounts.find(a => a.id === snapshot.settings.defaultAccountId && !a.archived)
  const [form, setForm] = useState({ name: existing?.name || '', accountId: existing?.accountId || defaultAccount?.id || '', projectId: existing?.projectId || (projectId !== 'geral' ? projectId : snapshot.projects.find(p => !p.archived)?.id || ''), categoryId: existing?.categoryId || snapshot.categories.find(c => c.type === 'expense' && !c.parentId && !c.archived)?.id || '', currency: existing?.currency || defaultAccount?.currency || 'BRL', notes: existing?.notes || '' })
  const [variable, setVariable] = useState(existing ? existing.amountCents === null : Boolean(recurring))
  const [amount, setAmount] = useState(existing?.amountCents ? moneyDecimal(existing.amountCents) : '')
  const [estimate, setEstimate] = useState(moneyDecimal(existing?.estimateCents || 0))
  const [dueDate, setDueDate] = useState(bill?.dueDate || template?.startDate || today())
  const [endDate, setEndDate] = useState(template?.endDate || '')
  const [estimateMode, setEstimateMode] = useState<Commitment['estimateMode']>(template?.estimateMode || 'last')
  const [busy, setBusy] = useState(false)
  const change = (value: Partial<typeof form>) => setForm(f => ({ ...f, ...value }))
  return <PlanningDialog title={recurring ? template ? 'Editar recorrência' : 'Novo compromisso mensal' : bill ? 'Editar conta' : 'Nova conta a pagar'} busy={busy} onClose={onClose}><form className="stack" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); const ok = await onCommit(async () => {
    const data = { ...form, accountId: form.accountId || null, amountCents: variable ? null : parseMoney(amount), estimateCents: parseMoney(estimate || '0') }
    return recurring ? api.saveCommitment({ ...data, id: template?.id, startDate: dueDate, endDate: endDate || null, estimateMode, paused: template?.paused || false }) : api.saveBill({ ...data, id: bill?.id, dueDate })
  }, recurring ? 'Compromisso salvo. As próximas ocorrências já estão disponíveis.' : 'Conta salva.'); setBusy(false); if (ok) onClose() }}>
    <label className="field">Nome da conta<input required maxLength={300} autoFocus value={form.name} onChange={e => change({ name: e.target.value })} placeholder="Energia, aluguel, internet…" /></label>
    <div className="form-grid"><label className="field">{recurring ? 'Primeiro vencimento' : 'Vencimento'}<input type="date" required disabled={Boolean(template)} value={dueDate} onChange={e => setDueDate(e.target.value)} /></label>{recurring && <label className="field">Repetir até · opcional<input type="date" min={dueDate} value={endDate} onChange={e => setEndDate(e.target.value)} /></label>}</div>
    <label className="checkbox-field"><input type="checkbox" disabled={Boolean(bill?.loanId)} checked={variable} onChange={e => setVariable(e.target.checked)} />{recurring ? 'O valor muda a cada mês' : 'Ainda não sei o valor'}</label>
    <div className="form-grid">{variable ? <MoneyField label={`Previsão inicial (${form.currency}) · não é dívida confirmada`} value={estimate} onChange={setEstimate} /> : <MoneyField label={`Valor confirmado (${form.currency})`} value={amount} onChange={setAmount} disabled={Boolean(bill?.loanId)} />}{recurring && variable && <label className="field">Previsão das próximas contas<select aria-label="Previsão das próximas contas" value={estimateMode} onChange={e => setEstimateMode(e.target.value as Commitment['estimateMode'])}><option value="last">Última fatura confirmada</option><option value="average">Média das últimas 3 faturas</option><option value="manual">Previsão informada</option></select></label>}<PlanningReferences snapshot={snapshot} {...form} onChange={change} onCommit={onCommit} preferredDate={bill?.dueDate || template?.startDate || today()} /></div>
    <label className="field">Observações / referência do boleto<textarea value={form.notes} maxLength={4000} onChange={e => change({ notes: e.target.value })} /></label>
    <p className="hint">{recurring ? 'Novas ocorrências são geradas até dois meses à frente enquanto a recorrência estiver ativa. Alterar o modelo não reescreve as faturas existentes. Pausar mantém as já criadas.' : 'Confirmar o valor provisiona a saída. O saldo bancário só muda quando você registra o pagamento.'}</p>
    <button className="primary" disabled={busy} type="submit">{busy ? 'Salvando…' : recurring ? 'Salvar compromisso' : 'Salvar conta'}</button>
  </form></PlanningDialog>
}
function PaymentEditor({ snapshot, bill, onCommit, onClose }: { snapshot: Snapshot; bill: Bill; onCommit: Commit; onClose: () => void }) {
  const [accountId, setAccount] = useState(bill.accountId || snapshot.settings.defaultAccountId || '')
  const [paidDate, setDate] = useState(today()), [covered, setCovered] = useState(moneyDecimal(billRemaining(snapshot, bill) || 0))
  const [interest, setInterest] = useState('0'), [fine, setFine] = useState('0'), [fee, setFee] = useState('0'), [discount, setDiscount] = useState('0')
  const [customTotal, setCustomTotal] = useState(''), [notes, setNotes] = useState(''), [busy, setBusy] = useState(false)
  const [requestId] = useState(() => crypto.randomUUID())
  let calculated = 0, adjustment = 0, valid = true
  try { calculated = parseMoney(covered) + parseMoney(interest) + parseMoney(fine) + parseMoney(fee) - parseMoney(discount); adjustment = customTotal ? parseMoney(customTotal) - calculated : 0 } catch { valid = false }
  return <PlanningDialog title="Registrar pagamento" busy={busy} onClose={onClose}><form className="stack" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); const ok = await onCommit(() => api.payBill({ requestId, billId: bill.id, accountId, paidDate, appliedCents: parseMoney(covered), interestCents: parseMoney(interest), fineCents: parseMoney(fine), feeCents: parseMoney(fee), discountCents: parseMoney(discount), ...(customTotal ? { totalCents: parseMoney(customTotal) } : {}), notes }), 'Pagamento registrado. Saldo e pendência atualizados.'); setBusy(false); if (ok) onClose() }}>
    <div className="payment-title"><h3>{bill.name}</h3><p className="hint">Vencimento {dateLabel(bill.dueDate)} · pendente {money(billRemaining(snapshot, bill) || 0, bill.currency)}</p></div>
    <div className="form-grid"><label className="field">Conta de pagamento<select aria-label="Conta de pagamento" required value={accountId} onChange={e => setAccount(e.target.value)}><option value="">Escolher conta</option>{snapshot.accounts.filter(a => !a.archived && (a.currency || 'BRL') === bill.currency).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="field">Data do pagamento<input type="date" required max={today()} value={paidDate} onChange={e => setDate(e.target.value)} /></label><MoneyField label="Valor da conta a quitar · permite baixa parcial" value={covered} onChange={setCovered} /><MoneyField label="Juros adicionais" value={interest} onChange={setInterest} /><MoneyField label="Multa" value={fine} onChange={setFine} /><MoneyField label="Outras taxas" value={fee} onChange={setFee} /><MoneyField label="Desconto" value={discount} onChange={setDiscount} /><MoneyField label="Total pago personalizado · opcional" required={false} value={customTotal} onChange={setCustomTotal} /></div>
    <div className="payment-total"><span>Total que sai da conta</span><strong className="metric">{valid ? money(calculated + adjustment, bill.currency) : 'Revise os valores'}</strong>{valid && adjustment !== 0 && <small>Ajuste não classificado: {money(adjustment, bill.currency)}. Não será presumido como juros.</small>}</div>
    <label className="field">Observações / referência do comprovante<textarea maxLength={4000} value={notes} onChange={e => setNotes(e.target.value)} /></label><p className="hint">Este registro não executa um pagamento bancário. Em parcelas, os encargos contratuais já estão no valor da conta; informe acima somente acréscimos. Baixas parciais distribuem principal e encargos contratuais proporcionalmente.</p><button className="primary" type="submit" disabled={busy || !valid}>Confirmar pagamento</button>
  </form></PlanningDialog>
}
export default function Bills({ snapshot, projectId, onCommit }: Props) {
  const displayCurrency = useCurrency()
  const [filter, setFilter] = useState('open'), [search, setSearch] = useState(''), [view, setView] = useState('list'), [month, setMonth] = useState(today().slice(0, 7))
  const [editor, setEditor] = useState<{ bill?: Bill; template?: Commitment; recurring?: boolean } | null>(null), [paying, setPaying] = useState<string | null>(null), [details, setDetails] = useState<string | null>(null), [busy, setBusy] = useState(false)
  const bills = (snapshot.bills || []).filter(b => projectId === 'geral' || b.projectId === projectId)
  const loose = snapshot.transactions.filter(t => t.type === 'expense' && t.status === 'pending' && !t.billId && (projectId === 'geral' || t.projectId === projectId))
  const isPaid = (b: Bill) => billRemaining(snapshot, b) === 0
  const open = bills.filter(b => !b.canceled && !isPaid(b))
  const missing = new Set<string>()
  const convert = (value: number, currency: string) => { const result = exchange(snapshot, value, currency, displayCurrency); if (result === null) missing.add(currency); return Math.round(result || 0) }
  const confirmed = open.reduce((sum, b) => sum + convert(billRemaining(snapshot, b) || 0, b.currency), 0) + loose.reduce((sum, t) => sum + convert(t.amountCents, snapshot.accounts.find(a => a.id === t.accountId)?.currency || 'BRL'), 0)
  const estimate = open.filter(b => b.amountCents === null).reduce((sum, b) => sum + convert(b.estimateCents, b.currency), 0)
  const horizon = new Date(`${today()}T12:00:00`); horizon.setDate(horizon.getDate() + 7)
  const nextWeek = `${horizon.getFullYear()}-${String(horizon.getMonth() + 1).padStart(2, '0')}-${String(horizon.getDate()).padStart(2, '0')}`
  const visible = bills.filter(b => b.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()) && (filter === 'all' || filter === 'canceled' ? filter === 'all' || b.canceled : !b.canceled && (filter === 'paid' ? isPaid(b) : !isPaid(b) && (filter === 'unknown' ? b.amountCents === null : filter === 'overdue' ? b.dueDate < today() : filter === 'today' ? b.dueDate === today() : filter === 'week' ? b.dueDate >= today() && b.dueDate <= nextWeek : true)))).sort((a, b) => a.dueDate.localeCompare(b.dueDate))
  const run = async (action: () => Promise<unknown>, message: string) => { if (busy) return; setBusy(true); await onCommit(action, message); setBusy(false) }
  const adopt = async (entry: Transaction) => { let bill: Bill | undefined; const ok = await onCommit(async () => { bill = await api.adoptBill({ id: entry.id }) }, 'Conta vinculada sem duplicar o lançamento.'); if (ok && bill) setDetails(bill.id) }
  const payingBill = bills.find(b => b.id === paying)
  const renderBill = (b: Bill) => {
    const remaining = billRemaining(snapshot, b), account = snapshot.accounts.find(a => a.id === b.accountId)
    const payments = (snapshot.payments || []).filter(p => p.billId === b.id)
    return <article key={b.id} className={`bill-row ${isPaid(b) ? 'bill-paid' : ''} ${b.canceled ? 'bill-canceled' : ''}`}>
      <div className="bill-date"><strong>{b.dueDate.slice(8)}</strong><small>{new Date(`${b.dueDate}T12:00:00`).toLocaleDateString('pt-BR', { month: 'short' })}</small></div><div className="bill-description"><button className="text-button" aria-expanded={details === b.id} onClick={() => setDetails(details === b.id ? null : b.id)}>{b.name}</button><small>{account?.name || 'Sem conta definida'} · {b.creditCardId ? 'Parcela de cartão' : b.templateId ? 'Recorrente' : b.loanId ? 'Parcela de contrato' : 'Conta avulsa'}</small><span className={`badge ${!b.canceled && !isPaid(b) && b.dueDate < today() ? 'negative' : isPaid(b) ? 'positive' : ''}`}>{b.canceled ? 'Cancelada' : isPaid(b) ? 'Paga' : b.amountCents === null ? 'Aguardando valor' : payments.length ? 'Parcialmente paga' : b.dueDate < today() ? 'Vencida' : 'A pagar'}</span></div><div className="bill-value"><strong>{remaining === null ? '—' : money(isPaid(b) ? payments.reduce((sum, p) => sum + p.totalCents, 0) : remaining, b.currency)}</strong>{remaining === null && <small>Previsão: {money(b.estimateCents, b.currency)}</small>}{remaining !== null && payments.length > 0 && <small>Original: {money(b.amountCents || 0, b.currency)}</small>}</div>
      <div className="row-actions">{!b.canceled && !isPaid(b) && <>{remaining === null ? <button className="secondary" onClick={() => setEditor({ bill: b })}>Informar valor</button> : <><button className="secondary quick-payment" title={`Registrar hoje ${money(remaining, b.currency)} em ${account?.name || 'conta não definida'}`} disabled={busy || !account || account.archived} onClick={() => void run(() => api.payBill({ requestId: crypto.randomUUID(), billId: b.id, accountId: account?.id, paidDate: today() }), 'Pagamento registrado. Você pode desfazer no detalhe da conta.')}><Check size={15} />Marcar como pago</button><button className="icon-button" aria-label={`Pagamento personalizado de ${b.name}`} title="Pagamento personalizado" onClick={() => setPaying(b.id)}><SlidersHorizontal size={16} /></button></>}</>}<button className="text-button" onClick={() => setDetails(details === b.id ? null : b.id)}>Detalhes</button></div>
      {details === b.id && <div className="bill-details"><p>{b.notes || 'Sem observações.'}</p><Attachments snapshot={snapshot} ownerType="bill" ownerId={b.id} onCommit={onCommit} /><p className="hint">Vencimento: {dateLabel(b.dueDate)}. Baixas usam a conta e a data informadas no pagamento.</p><div className="toolbar"><button className="secondary" disabled={busy} onClick={() => b.creditCardId ? void onCommit(() => api.saveSettings({ screen: 'cards' }), '') : setEditor({ bill: b })}>{b.creditCardId ? 'Gerenciar compra no cartão' : 'Editar conta'}</button>{!b.loanId && !b.creditCardId && !payments.length && <button className="secondary" disabled={busy} onClick={() => void run(() => api.cancelBill({ id: b.id, canceled: !b.canceled }), b.canceled ? 'Conta reaberta.' : 'Ocorrência cancelada. A recorrência não foi alterada.')}>{b.canceled ? 'Reabrir conta' : 'Cancelar ocorrência'}</button>}</div>{payments.map((p, index) => <div className="payment-record" key={p.id}><div><strong>{money(p.totalCents, b.currency)} · {dateLabel(p.paidDate)}</strong><small>{snapshot.accounts.find(a => a.id === p.accountId)?.name} · baixa {money(p.appliedCents, b.currency)}</small><small>Juros {money(p.interestCents, b.currency)} · multa {money(p.fineCents, b.currency)} · taxas {money(p.feeCents, b.currency)} · desconto {money(p.discountCents, b.currency)} · ajuste {money(p.adjustmentCents, b.currency)}</small>{b.loanId && <small>Amortização: {money(p.principalCents, b.currency)} · custo financeiro: {money(p.totalCents - p.principalCents, b.currency)}</small>}{p.notes && <small>{p.notes}</small>}</div><button className="secondary" disabled={busy || index !== payments.length - 1} onClick={() => void run(() => api.undoPayment({ id: p.id }), 'Baixa desfeita e saldo revertido.')}><Undo2 size={14} />Desfazer baixa</button></div>)}</div>}
    </article>
  }
  return <div className="stack planning-page">
    <div className="planning-summary"><article className="stat-card"><span className="muted">Confirmado a pagar</span><strong className="metric"><AnimatedMoney cents={confirmed} /></strong><small>Todas as pendências do projeto</small></article><article className="stat-card"><span className="muted">Previsões · aguardando valor</span><strong className="metric"><AnimatedMoney cents={estimate} /></strong><small>Separadas do saldo e das dívidas confirmadas</small></article><article className="stat-card"><span className="muted">Precisam de atenção</span><strong className="metric">{open.filter(b => b.dueDate <= today()).length + loose.filter(t => t.dueDate <= today()).length}</strong><small>Vencidas ou vencendo hoje</small></article></div>{missing.size > 0 && <p className="error-text">Totais parciais: falta câmbio de {Array.from(missing).join(', ')}.</p>}
    <section className="card"><div className="section-heading"><div><h2>Uma rotina mais leve</h2><p className="hint">Confirme o valor quando a fatura chegar. Dê baixa quando o pagamento acontecer.</p></div><div className="toolbar"><button className="secondary" onClick={() => setEditor({ recurring: true })}><Repeat2 size={16} />Novo compromisso mensal</button><button className="primary" onClick={() => setEditor({})}><Plus size={16} />Nova conta</button></div></div><div className="bills-toolbar"><label className="field">Buscar conta<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nome da conta" /></label><label className="field">Situação<select aria-label="Situação" value={filter} onChange={e => setFilter(e.target.value)}>{[['open', 'Em aberto'], ['overdue', 'Vencidas'], ['today', 'Hoje'], ['week', 'Próximos 7 dias'], ['unknown', 'Aguardando valor'], ['paid', 'Pagas'], ['canceled', 'Canceladas'], ['all', 'Todas']].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><div className="field"><label htmlFor="bills-default-account">Conta padrão para novos compromissos</label><select id="bills-default-account" aria-label="Conta padrão para novos compromissos" value={snapshot.settings.defaultAccountId || ''} disabled={busy} onChange={e => void run(() => api.saveSettings({ defaultAccountId: e.target.value || null }), 'Conta padrão atualizada. Contas existentes mantêm sua escolha.')}><option value="">Nenhuma</option>{snapshot.accounts.filter(a => !a.archived).map(a => <option key={a.id} value={a.id}>{a.name} · {a.currency || 'BRL'}</option>)}</select><InlineCreate kind="account" snapshot={snapshot} onCommit={onCommit} onCreated={id => void run(() => api.saveSettings({ defaultAccountId: id }), 'Conta padrão atualizada.')} disabled={busy} /></div><div className="chart-pills"><button aria-label="Ver lista de contas" aria-pressed={view === 'list'} onClick={() => setView('list')}><Clock3 size={17} /></button><button aria-label="Ver calendário de contas" aria-pressed={view === 'calendar'} onClick={() => setView('calendar')}><CalendarDays size={17} /></button></div></div>
    {view === 'list' ? <div className="bills-list">{visible.map(renderBill)}{!visible.length && <p className="empty-state">Nenhuma conta neste filtro. Cadastre uma conta avulsa ou um compromisso mensal.</p>}</div> : <><div className="calendar-heading"><button className="icon-button" aria-label="Mês anterior" onClick={() => setMonth(nextMonth(`${month}-01`, -1).slice(0, 7))}>←</button><label className="field">Mês do calendário<input type="month" value={month} onChange={e => { if (e.target.value) setMonth(e.target.value) }} /></label><button className="icon-button" aria-label="Próximo mês" onClick={() => setMonth(nextMonth(`${month}-01`, 1).slice(0, 7))}>→</button></div><div className="bills-calendar">{['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'].map(d => <span key={d}>{d}</span>)}{Array.from({ length: new Date(`${month}-01T12:00:00`).getDay() }, (_, i) => <div key={`empty-${i}`} />)}{Array.from({ length: new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate() }, (_, i) => { const day = `${month}-${String(i + 1).padStart(2, '0')}`; return <div className={day === today() ? 'calendar-today' : ''} key={day}><strong>{i + 1}</strong>{visible.filter(b => b.dueDate === day).map(b => <button key={b.id} onClick={() => { setDetails(b.id); setView('list') }}>{b.name}<small>{b.amountCents === null ? 'Aguardando valor' : money(billRemaining(snapshot, b) || b.amountCents, b.currency)}</small></button>)}</div> })}</div></>}
    </section>
    {loose.length > 0 && <section className="card"><h2>Despesas pendentes do histórico</h2><p className="hint">Os lançamentos antigos já estão no total confirmado. Vincule uma vez para usar baixas parciais e encargos, sem duplicação.</p>{loose.map(t => <div className="legacy-bill" key={t.id}><span>{t.description}<small>{dateLabel(t.dueDate)} · {money(t.amountCents, snapshot.accounts.find(a => a.id === t.accountId)?.currency || 'BRL')}</small></span><button className="secondary" onClick={() => void adopt(t)}>Gerenciar pagamento</button></div>)}</section>}
    <section className="card"><h2>Seus compromissos mensais</h2><p className="hint">Lembretes dentro do aplicativo, sem precisar saber o valor antecipadamente. As ocorrências aparecem ao abrir ou atualizar o Purple Tab; não há alerta com o aplicativo fechado.</p>{(snapshot.commitments || []).filter(t => projectId === 'geral' || t.projectId === projectId).map(t => <div className="legacy-bill" key={t.id}><span>{t.name}<small>Todo dia {t.startDate.slice(8)} · {t.amountCents === null ? 'Variável' : money(t.amountCents, t.currency)} · {t.paused ? 'Pausado' : 'Ativo'}</small></span><div className="row-actions"><button className="secondary" onClick={() => setEditor({ recurring: true, template: t })}>Editar recorrência</button><button className="secondary" disabled={busy} onClick={() => void run(() => api.saveCommitment({ ...t, paused: !t.paused }), t.paused ? 'Recorrência retomada.' : 'Recorrência pausada. Faturas existentes preservadas.')}>{t.paused ? 'Retomar' : 'Pausar'}</button></div></div>)}</section>
    {editor && <BillEditor {...{ snapshot, projectId, onCommit }} {...editor} onClose={() => setEditor(null)} />}{payingBill && <PaymentEditor snapshot={snapshot} bill={payingBill} onCommit={onCommit} onClose={() => setPaying(null)} />}
  </div>
}
