import { useState } from 'react'
import Attachments from './Attachments'
import { Plus, Gem, Trash2 } from 'lucide-react'
import { api } from '../lib/api'
import type { Commit, PropertyAsset, Snapshot } from '../lib/types'
import { dateLabel, money, moneyDecimal, parseMoney, today } from '../lib/finance'
import { loanBalance, netWorth } from '../lib/planning'
import { currencies } from '../lib/investments'
import { useCurrency } from '../lib/CurrencyContext'
import AnimatedMoney from '../components/motion/AnimatedMoney'
import { Identity, IconPicker } from './Identity'
import { MoneyField, PlanningDialog } from './PlanningShared'
import InlineCreate from './InlineCreate'

interface Props { snapshot: Snapshot; projectId: string; onCommit: Commit }
function PropertyEditor({ snapshot, projectId, asset, onCommit, onClose }: Props & { asset?: PropertyAsset; onClose: () => void }) {
  const [form, setForm] = useState({ name: asset?.name || '', kind: asset?.kind || 'Imóvel', icon: asset?.icon || 'home', currency: asset?.currency || 'BRL', projectId: asset?.projectId || (projectId === 'geral' ? '' : projectId), acquisitionDate: asset?.acquisitionDate || today(), ownership: String(asset?.ownershipPercent || 100), loanId: asset?.loanId || '', notes: asset?.notes || '' })
  const [cost, setCost] = useState(asset ? moneyDecimal(asset.acquisitionCents) : ''), [busy, setBusy] = useState(false)
  const [values, setValues] = useState(asset ? asset.valuations.map(v => ({ date: v.date, value: moneyDecimal(v.valueCents), source: v.source })) : [{ date: today(), value: '', source: 'Estimativa pessoal' }])
  const change = (data: Partial<typeof form>) => setForm(f => ({ ...f, ...data }))
  return <PlanningDialog title={asset ? 'Editar patrimônio e avaliações' : 'Adicionar patrimônio'} busy={busy} onClose={onClose}><form className="stack" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); const ok = await onCommit(() => api.saveProperty({ ...form, id: asset?.id, projectId: form.projectId || null, loanId: form.loanId || null, acquisitionCents: parseMoney(cost), ownershipPercent: Number(form.ownership), archived: asset?.archived || false, valuations: values.map(v => ({ date: v.date, valueCents: parseMoney(v.value), source: v.source })) }), 'Patrimônio e avaliações salvos.'); setBusy(false); if (ok) onClose() }}>
    <div className="form-grid"><label className="field">Nome do bem<input autoFocus required maxLength={300} value={form.name} onChange={e => change({ name: e.target.value })} placeholder="Apartamento, carro, terreno…" /></label><label className="field">Categoria do patrimônio<input aria-label="Categoria do patrimônio" list="property-kinds" required maxLength={100} value={form.kind} onChange={e => change({ kind: e.target.value })} /><datalist id="property-kinds">{['Imóvel', 'Veículo', 'Terreno', 'Equipamento', 'Coleção', 'Participação societária', 'Outro'].map(k => <option key={k}>{k}</option>)}</datalist></label><label className="field">Moeda do bem<select aria-label="Moeda do bem" value={form.currency} onChange={e => change({ currency: e.target.value, loanId: '' })}>{currencies.map(c => <option key={c}>{c}</option>)}</select></label><div className="field"><label htmlFor="property-project">Projeto do bem</label><select id="property-project" aria-label="Projeto do bem" value={form.projectId} onChange={e => change({ projectId: e.target.value })}><option value="">Patrimônio geral</option>{snapshot.projects.filter(p => !p.archived || p.id === form.projectId).map(p => <option value={p.id} key={p.id}>{p.name}</option>)}</select><InlineCreate kind="project" snapshot={snapshot} onCommit={onCommit} onCreated={id => change({ projectId: id })} disabled={busy} /></div><label className="field">Data de aquisição<input required type="date" max={today()} value={form.acquisitionDate} onChange={e => change({ acquisitionDate: e.target.value })} /></label><MoneyField label="Preço de aquisição do bem inteiro" value={cost} onChange={setCost} /><label className="field">Sua participação (%)<input required type="number" min="0.01" max="100" step="0.01" value={form.ownership} onChange={e => change({ ownership: e.target.value })} /></label><label className="field">Financiamento vinculado<select aria-label="Financiamento vinculado" value={form.loanId} onChange={e => change({ loanId: e.target.value })}><option value="">Sem financiamento</option>{(snapshot.loans || []).filter(l => l.currency === form.currency).map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><IconPicker value={form.icon} onChange={value => change({ icon: value })} />
    <fieldset className="stack"><legend>Histórico de avaliações</legend><p className="hint">Informe o valor do bem inteiro. O consolidado considera apenas sua participação. Avaliações não movimentam caixa nem geram renda.</p>{values.map((v, index) => <div className="valuation-row" key={index}><label className="field">Data da avaliação {index + 1}<input required type="date" min={form.acquisitionDate} max={today()} value={v.date} onChange={e => setValues(rows => rows.map((r, i) => i === index ? { ...r, date: e.target.value } : r))} /></label><MoneyField label={`Valor estimado ${index + 1}`} value={v.value} onChange={value => setValues(rows => rows.map((r, i) => i === index ? { ...r, value } : r))} /><label className="field">Fonte / referência {index + 1}<input maxLength={300} value={v.source} onChange={e => setValues(rows => rows.map((r, i) => i === index ? { ...r, source: e.target.value } : r))} /></label><button type="button" className="icon-button" aria-label={`Remover avaliação ${index + 1}`} disabled={values.length === 1} onClick={() => setValues(rows => rows.filter((_, i) => i !== index))}><Trash2 size={15} /></button></div>)}<button type="button" className="secondary" onClick={() => setValues(rows => [...rows, { date: today(), value: '', source: '' }])}>Adicionar avaliação</button></fieldset><label className="field">Observações / documentos de referência<textarea maxLength={4000} value={form.notes} onChange={e => change({ notes: e.target.value })} /></label><p className="hint">O cadastro é patrimonial: não cria uma despesa de compra. O contrato vinculado deve representar a dívida que é sua, não a dívida de outros coproprietários.</p><button className="primary" type="submit" disabled={busy}>Salvar patrimônio</button>
  </form></PlanningDialog>
}
export default function Patrimony({ snapshot, projectId, onCommit }: Props) {
  const currency = useCurrency(), total = netWorth(snapshot, currency, projectId)
  const [editor, setEditor] = useState<PropertyAsset | 'new' | null>(null), [archived, setArchived] = useState(false), [search, setSearch] = useState('')
  const assets = (snapshot.assets || []).filter(a => (projectId === 'geral' || a.projectId === projectId) && (archived || !a.archived) && `${a.name} ${a.kind}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  return <div className="stack planning-page"><section className="card patrimony-hero"><div><span className="eyebrow">O QUE VOCÊ CONSTRUIU</span><h2>Patrimônio líquido{total.missing.length > 0 ? ' · parcial' : ''}</h2><strong className="metric"><AnimatedMoney cents={total.net} /></strong><p className="hint">Contas + investimentos + sua participação nos bens − principal dos contratos e compras pendentes no crédito.</p></div><button className="primary" onClick={() => setEditor('new')}><Plus size={16} />Adicionar patrimônio</button></section>{total.missing.length > 0 && <p role="status" className="error-text">Sem avaliação ou câmbio disponível: {total.missing.join(', ')}. Esses itens não foram somados.</p>}
    <div className="planning-summary four">{[['Contas bancárias', total.cash], ['Investimentos', total.investments], ['Bens · sua participação', total.assets], ['Dívidas · contratos e cartões', total.debt]].map(([label, value]) => <article className="stat-card" key={label}><span className="muted">{label}</span><strong className="metric"><AnimatedMoney cents={Number(value)} /></strong></article>)}</div>
    <p className="hint">{projectId !== 'geral' ? 'Neste projeto, contas bancárias globais não são incluídas. Só entram bens, investimentos e contratos vinculados ao projeto. ' : ''}Investimentos já cadastrados entram automaticamente; não os cadastre novamente como bens. O saldo da conta deve excluir o dinheiro já aplicado. Câmbio atual de referência; avaliações são estimativas. Dívidas são descontadas uma única vez, vinculadas ou não a um bem. Compras pendentes no crédito entram integralmente na dívida, incluindo parcelas futuras. Contas de consumo fora do cartão e juros futuros de contratos não entram neste indicador.</p>
    <section className="card"><div className="section-heading"><h2>Seus bens</h2><div className="toolbar"><label className="field">Buscar patrimônio<input value={search} onChange={e => setSearch(e.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={archived} onChange={e => setArchived(e.target.checked)} />Mostrar arquivados</label></div></div><div className="property-grid">{assets.map(asset => { const latest = asset.valuations.at(-1)!, loan = snapshot.loans?.find(l => l.id === asset.loanId), owned = Math.round(latest.valueCents * asset.ownershipPercent / 100), debt = loan ? loanBalance(snapshot, loan) : 0; return <article className={`property-card ${asset.archived ? 'bill-canceled' : ''}`} key={asset.id}><div className="section-heading"><Identity value={asset.icon} name={asset.name} size={46} /><span className="badge">{asset.kind}</span></div><h3>{asset.name}</h3><span className="muted">Sua participação · {asset.ownershipPercent}%</span><strong className="metric"><AnimatedMoney currency={asset.currency} cents={owned} /></strong><dl><div><dt>Valor do bem inteiro</dt><dd>{money(latest.valueCents, asset.currency)}</dd></div><div><dt>Aquisição do bem inteiro</dt><dd>{money(asset.acquisitionCents, asset.currency)}</dd></div><div><dt>Dívida vinculada</dt><dd>{money(debt, asset.currency)}</dd></div><div><dt>Sua posição líquida</dt><dd>{money(owned - debt, asset.currency)}</dd></div></dl><small className="hint">Avaliado em {dateLabel(latest.date)} · {latest.source || 'Sem fonte informada'}</small><div className="toolbar"><button className="secondary" onClick={() => setEditor(asset)}>Editar / avaliar</button><button className="text-button" onClick={() => void onCommit(() => api.saveProperty({ ...asset, archived: !asset.archived }), asset.archived ? 'Bem reativado.' : 'Bem arquivado. A dívida vinculada permanece no consolidado.')}>{asset.archived ? 'Reativar' : 'Arquivar'}</button></div><details><summary>{asset.valuations.length} avaliação(ões) · histórico</summary>{asset.valuations.map(v => <p key={v.date}>{dateLabel(v.date)} · {money(v.valueCents, asset.currency)}<small className="cell-secondary">{v.source}</small></p>)}<p className="hint">{asset.notes}</p><Attachments snapshot={snapshot} ownerType="property" ownerId={asset.id} onCommit={onCommit} /></details></article> })}</div>{!assets.length && <div className="empty-state"><Gem size={30} /><p>Imóveis, veículos e outros bens, com valores e histórico próprios.</p></div>}</section>
    {editor && <PropertyEditor {...{ snapshot, projectId, onCommit }} asset={editor === 'new' ? undefined : editor} onClose={() => setEditor(null)} />}
  </div>
}
