import { useState } from 'react'
import { Database, Download, FolderCog, RotateCcw, ShieldCheck, UserRound } from 'lucide-react'
import { api } from '../lib/api'
import type { Commit, Snapshot } from '../lib/types'

export default function Preferences({ snapshot, onCommit, onManage }: { snapshot: Snapshot; onCommit: Commit; onManage: () => void }) {
  const [name, setName] = useState(snapshot.settings.profileName)
  const [busy, setBusy] = useState(false)
  const action = async (callback: () => Promise<unknown>, success: string) => { if (busy) return; setBusy(true); try { await onCommit(callback, success) } finally { setBusy(false) } }
  return <div className="settings-grid">
    <section className="card"><div className="section-heading"><h2><UserRound size={20} />Seu perfil</h2><span className="badge">Local</span></div><form onSubmit={e => { e.preventDefault(); void action(() => api.saveSettings({ profileName: name.trim() }), 'Perfil atualizado.') }} className="stack"><label className="field">Como podemos chamar você?<input required maxLength={80} value={name} onChange={e => setName(e.target.value)} placeholder="Seu nome" /></label><div className="field"><span>Idioma e moedas</span><div className="settings-value">Português (Brasil) · múltiplas moedas</div></div><label className="checkbox-field"><input type="checkbox" checked={snapshot.settings.compact} disabled={busy} onChange={e => void action(() => api.saveSettings({ compact: e.target.checked }), '')} />Usar interface compacta</label><button className="button primary" disabled={busy || !name.trim()} type="submit">Salvar perfil</button></form></section>
    <section className="card"><div className="section-heading"><h2><FolderCog size={20} />Organização</h2></div><p className="muted">Cadastre contas, projetos e categorias para organizar cada lançamento. Cadastros arquivados continuam disponíveis no histórico.</p><div className="settings-counts"><span><strong>{snapshot.projects.length}</strong> projetos</span><span><strong>{snapshot.accounts.length}</strong> contas</span><span><strong>{snapshot.categories.filter(c => !c.parentId).length}</strong> categorias</span></div><button className="button secondary" onClick={onManage}>Gerenciar cadastros</button></section>
    <section className="card span-2"><div className="section-heading"><h2><ShieldCheck size={20} />Backup e recuperação</h2><span className="badge">SQLite local</span></div><p>Uma cópia automática é criada por dia de uso. As últimas 14 cópias diárias ficam na pasta de backups ao lado do banco.</p><p className="hint">Último backup: {snapshot.meta.lastBackup ? new Date(snapshot.meta.lastBackup).toLocaleString('pt-BR') : 'Ainda não realizado'}. Guarde também uma cópia manual em outro local.</p>{snapshot.meta.backupWarning && <p className="error-text" role="alert">{snapshot.meta.backupWarning}</p>}<div className="toolbar"><button className="button primary" disabled={busy} onClick={() => void action(() => api.backup(), 'Backup salvo com sucesso.')}><Download size={17} />Salvar backup</button><button className="button secondary" disabled={busy} onClick={() => void action(() => api.restore(), 'Backup restaurado. Seus dados foram atualizados.')}><RotateCcw size={17} />Restaurar backup</button></div><p className="hint">A restauração substitui os dados atuais. O aplicativo pedirá confirmação e criará uma cópia preventiva.</p></section>
    <section className="card span-2"><div className="section-heading"><h2><Database size={20} />Dados deste computador</h2><span className="badge">v{snapshot.meta.appVersion}</span></div><p className="path-display">{snapshot.meta.databasePath}</p><p className="muted">Os dados são salvos automaticamente após cada operação. O aplicativo funciona sem internet e a base fica separada do executável.</p></section>
  </div>
}
