/* global window, document */
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { _electron } from 'playwright'
import electron from 'electron'

const temporary = mkdtempSync(join(tmpdir(), 'purple-cards-ui-')), root = resolve('.'), artifacts = join(root, 'tests', 'artifacts', `cards-${new Date().toISOString().replace(/[:.]/g, '-')}`)
mkdirSync(artifacts, { recursive: true })
const env = { ...process.env, PURPLE_TAB_DATA_DIR: join(temporary, 'data'), PURPLE_TAB_TEST_HEADLESS: '1' }; delete env.ELECTRON_RUN_AS_NODE
let app, page
const errors = []
try {
  app = await _electron.launch({ executablePath: process.env.PURPLE_TAB_EXE || electron, args: process.env.PURPLE_TAB_EXE ? [] : ['.'], cwd: root, env })
  page = await app.firstWindow(); page.setDefaultTimeout(12000); page.on('pageerror', e => errors.push(e.message))
  await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setSize(1460, 950); w.webContents.backgroundThrottling = false; w.showInactive() })
  await page.locator('.app-main').waitFor()
  await page.evaluate(async () => { await window.electronAPI.saveAccount({ name: 'Nubank', institution: 'Nubank', currency: 'BRL', type: 'checking', initialBalanceCents: 500000, initialDate: '2020-01-01', archived: false }) })
  await page.reload(); await page.locator('.app-main').waitFor()
  await page.getByRole('button', { name: 'Cartões', exact: true }).click()
  await page.getByRole('button', { name: 'Novo cartão', exact: true }).click()
  await page.getByLabel('Nome do cartão', { exact: true }).fill('Roxinho principal')
  await page.getByLabel('Instituição emissora', { exact: true }).fill('Nubank')
  await page.getByLabel('Últimos quatro dígitos · opcional', { exact: true }).fill('1234')
  await page.getByLabel('Limite total do cartão', { exact: true }).fill('3000')
  await page.getByLabel('Dia de fechamento', { exact: true }).fill('10')
  await page.getByLabel('Dia de vencimento', { exact: true }).fill('20')
  await page.getByLabel('Compras no dia do fechamento', { exact: true }).selectOption('next')
  await page.getByRole('button', { name: 'Salvar cartão', exact: true }).click()
  await page.locator('dialog').waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Novo lançamento', exact: true }).click()
  await page.getByLabel('Forma de pagamento', { exact: true }).selectOption('debit')
  await page.getByLabel('Descrição', { exact: true }).fill('Café no débito')
  await page.getByLabel('Valor (R$)', { exact: true }).fill('25')
  await page.getByLabel('Categoria', { exact: true }).selectOption({ label: 'Alimentação' })
  assert.equal(await page.getByLabel('Situação', { exact: true }).inputValue(), 'settled')
  await page.getByRole('button', { name: 'Criar lançamento', exact: true }).click()
  await page.locator('.modal-backdrop').waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Novo lançamento', exact: true }).click()
  await page.getByLabel('Forma de pagamento', { exact: true }).selectOption('credit')
  await page.getByLabel('Descrição da compra', { exact: true }).fill('Notebook parcelado')
  await page.getByLabel('Valor total da compra (BRL)', { exact: true }).fill('1200')
  await page.getByLabel('Parcelas · 1 para à vista', { exact: true }).fill('3')
  await page.getByLabel('Data da compra', { exact: true }).fill('2026-09-10')
  await page.getByLabel('Categoria da compra', { exact: true }).selectOption({ label: 'Outras despesas' })
  assert.match(await page.locator('.statement-preview').innerText(), /10\/10\/2026.*20\/10\/2026/)
  await page.screenshot({ path: join(artifacts, '01-compra-credito.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Registrar compra', exact: true }).click()
  await page.locator('.modal-backdrop').waitFor({ state: 'hidden' })
  let snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.cardPurchases.length, 1); assert.equal(snapshot.bills.length, 3)
  assert.equal(snapshot.transactions.filter(t => t.status === 'settled').length, 1)
  assert.equal(snapshot.transactions.find(t => t.status === 'settled').paymentMethod, 'debit')
  await page.waitForFunction(() => document.querySelector('.credit-card-tile .motion-number')?.getAttribute('data-value') === '180000')
  await page.getByRole('button', { name: 'Pagar fatura 10/2026', exact: true }).click()
  await page.getByLabel('Valor pago da fatura (BRL)', { exact: true }).fill('200')
  await page.getByRole('button', { name: 'Confirmar pagamento da fatura', exact: true }).click()
  await page.locator('dialog').waitFor({ state: 'hidden' })
  await page.waitForFunction(() => document.querySelector('.credit-card-tile .motion-number')?.getAttribute('data-value') === '200000')
  await page.locator('.statement-row').first().getByRole('button', { name: /10\/2026 ·/ }).click()
  await page.screenshot({ path: join(artifacts, '02-cartoes-parcial.png'), animations: 'disabled' })
  await page.getByRole('button', { name: 'Desfazer pagamento da fatura', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.credit-card-tile .motion-number')?.getAttribute('data-value') === '180000')
  await page.locator('.statement-row').first().getByRole('button', { name: 'Ajustar datas', exact: true }).click()
  await page.getByLabel('Fechamento desta fatura', { exact: true }).fill('2026-10-11')
  await page.getByLabel('Vencimento desta fatura', { exact: true }).fill('2026-10-22')
  await page.getByRole('button', { name: 'Salvar datas da fatura', exact: true }).click()
  await page.locator('dialog').waitFor({ state: 'hidden' })
  snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.bills[0].dueDate, '2026-10-22')
  await page.reload(); await page.locator('.credit-card-tile').waitFor()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 720))
  await page.screenshot({ path: join(artifacts, '03-cartoes-compacto.png'), animations: 'disabled' })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
  const settingsButton = await page.getByRole('button', { name: 'Configurações', exact: true }).boundingBox()
  assert.ok(settingsButton.y + settingsButton.height < 681)
  await page.getByRole('button', { name: 'Contas a pagar', exact: true }).click()
  await page.locator('.bill-row').first().getByRole('button', { name: 'Detalhes', exact: true }).click()
  await page.getByRole('button', { name: 'Gerenciar compra no cartão', exact: true }).click()
  await page.locator('.credit-card-tile').waitFor()
  assert.deepEqual(errors, [])
  writeFileSync(join(artifacts, 'result.json'), JSON.stringify({ status: 'passed', errors, tests: ['card-create', 'debit-payment-method', 'credit-from-expense-form', 'closing-day-preview', 'installments', 'used-and-available-limits', 'partial-payment', 'undo-payment', 'exceptional-dates', 'restart', '1000px-layout', 'bills-integration'], artifacts }, null, 2))
  console.log(JSON.stringify({ status: 'passed', artifacts }))
} catch (error) { if (page) await page.screenshot({ path: join(artifacts, 'failure.png'), animations: 'disabled' }).catch(() => {}); console.error(error); process.exitCode = 1 }
finally { await app?.close(); rmSync(temporary, { recursive: true, force: true }) }
