/* global window, document */
import assert from 'node:assert/strict'
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { resolve, join } from 'node:path'
import { _electron } from 'playwright'
import electron from 'electron'

const root = resolve('.'), temporary = mkdtempSync(join(tmpdir(), 'purple-planning-ui-')), data = join(temporary, 'data')
const artifacts = join(root, 'tests', 'artifacts', `planning-${new Date().toISOString().replace(/[:.]/g, '-')}`)
mkdirSync(artifacts, { recursive: true })
const env = { ...process.env, PURPLE_TAB_DATA_DIR: data, PURPLE_TAB_TEST_HEADLESS: '1' }; delete env.ELECTRON_RUN_AS_NODE
let app, page
const errors = []
try {
  app = await _electron.launch({ executablePath: process.env.PURPLE_TAB_EXE || electron, args: process.env.PURPLE_TAB_EXE ? [] : ['.'], cwd: root, env })
  page = await app.firstWindow(); page.setDefaultTimeout(12000); page.on('pageerror', e => errors.push(e.message))
  await app.evaluate(({ BrowserWindow }) => { const w = BrowserWindow.getAllWindows()[0]; w.setSize(1460, 950); w.webContents.backgroundThrottling = false; w.showInactive() })
  await page.locator('.app-main').waitFor()
  await page.evaluate(async () => {
    const api = window.electronAPI
    const a = await api.saveAccount({ name: 'Conta principal', institution: 'Nubank', currency: 'BRL', type: 'checking', initialBalanceCents: 100000, initialDate: '2020-01-01', archived: false })
    await api.saveAccount({ name: 'Conta alternativa', institution: 'Banco', currency: 'BRL', type: 'checking', initialBalanceCents: 100000, initialDate: '2020-01-01', archived: false })
    await api.saveSettings({ defaultAccountId: a.id })
  })
  await page.reload(); await page.locator('.balance-hero').waitFor()
  assert.equal(await page.locator('.dashboard-layout-toolbar').count(), 0)
  const trigger = page.getByRole('button', { name: 'Visualização do espaço de trabalho', exact: true })
  const bounds = await trigger.boundingBox(); assert.ok(bounds.width <= 40 && bounds.x > 1100)
  await trigger.click(); await page.locator('.workspace-presets').getByRole('button', { name: 'Mesa de gráficos', exact: true }).click()
  await page.locator('.workspace-popover').waitFor({ state: 'hidden' })
  await trigger.click(); await page.locator('.workspace-presets').getByRole('button', { name: 'Visão completa', exact: true }).click()
  await page.locator('.workspace-popover').waitFor({ state: 'hidden' })
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '01-dashboard-discreto.png') })
  await page.getByRole('button', { name: 'Contas a pagar', exact: true }).click()
  await page.getByRole('button', { name: 'Novo compromisso mensal', exact: true }).click()
  await page.getByLabel('Nome da conta', { exact: true }).fill('Energia mensal')
  await page.getByLabel('Primeiro vencimento', { exact: true }).fill('2026-09-15')
  await page.getByLabel('Previsão inicial (BRL) · não é dívida confirmada', { exact: true }).fill('180')
  await page.getByRole('button', { name: 'Salvar compromisso', exact: true }).click()
  await page.locator('dialog').waitFor({ state: 'hidden' })
  let snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.commitments.length, 1); assert.ok(snapshot.bills.length >= 2); assert.equal(snapshot.transactions.length, 0)
  let row = page.locator('.bill-row').filter({ hasText: 'Energia mensal' }).first()
  await row.getByRole('button', { name: 'Informar valor', exact: true }).click()
  await page.getByLabel('Ainda não sei o valor', { exact: true }).uncheck()
  await page.getByLabel('Valor confirmado (BRL)', { exact: true }).fill('200')
  await page.getByRole('button', { name: 'Salvar conta', exact: true }).click(); await page.locator('dialog').waitFor({ state: 'hidden' })
  row = page.locator('.bill-row').filter({ hasText: 'Energia mensal' }).first()
  await row.getByRole('button', { name: 'Pagamento personalizado de Energia mensal', exact: true }).click()
  await page.getByLabel('Conta de pagamento', { exact: true }).selectOption({ label: 'Conta alternativa' })
  await page.getByLabel('Valor da conta a quitar · permite baixa parcial', { exact: true }).fill('100')
  await page.getByLabel('Juros adicionais', { exact: true }).fill('5')
  await page.getByLabel('Total pago personalizado · opcional', { exact: true }).fill('108')
  await page.getByRole('button', { name: 'Confirmar pagamento', exact: true }).click(); await page.locator('dialog').waitFor({ state: 'hidden' })
  snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.payments[0].adjustmentCents, 300); assert.equal(snapshot.payments[0].totalCents, 10800)
  assert.equal(snapshot.transactions.find(t => t.status === 'pending').amountCents, 10000)
  await row.getByRole('button', { name: 'Detalhes', exact: true }).click()
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '02-baixa-parcial.png') })
  await row.getByRole('button', { name: 'Desfazer baixa', exact: true }).click()
  await page.waitForFunction(async () => !(await window.electronAPI.getSnapshot()).payments.length)
  await row.getByRole('button', { name: 'Marcar como pago', exact: true }).click()
  await page.waitForFunction(async () => (await window.electronAPI.getSnapshot()).payments.length === 1)
  await page.getByLabel('Situação', { exact: true }).selectOption('paid')
  row = page.locator('.bill-row').filter({ hasText: 'Energia mensal' }).first()
  await row.waitFor()
  const pdf = join(temporary, 'comprovante.pdf'); writeFileSync(pdf, '%PDF-1.4\nFixture do teste')
  await app.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }) }, pdf)
  if (!await row.locator('.bill-details').isVisible()) await row.getByRole('button', { name: 'Detalhes', exact: true }).click()
  await row.getByRole('button', { name: 'Anexar PDF / imagem', exact: true }).click()
  await row.locator('.attachment-row').filter({ hasText: 'comprovante.pdf' }).waitFor()
  await page.getByLabel('Situação', { exact: true }).selectOption('all')
  await page.getByRole('button', { name: 'Ver calendário de contas', exact: true }).click()
  await page.getByLabel('Mês do calendário', { exact: true }).fill('2026-09')
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '03-calendario.png') })
  await page.getByRole('button', { name: 'Financiamentos', exact: true }).click()
  await page.getByRole('button', { name: 'Novo contrato', exact: true }).click()
  await page.getByLabel('Nome do contrato', { exact: true }).fill('Financiamento do carro')
  await page.getByLabel('Valor originalmente contratado', { exact: true }).fill('10000')
  await page.getByLabel('Saldo devedor principal na data de referência', { exact: true }).fill('9000')
  await page.getByLabel('Data de referência', { exact: true }).fill('2026-01-01')
  await page.getByLabel('Quantidade de parcelas', { exact: true }).fill('3')
  await page.getByLabel('Primeira parcela', { exact: true }).fill('2026-09-30')
  await page.getByLabel('Encargos contratuais por parcela · ajustar abaixo', { exact: true }).fill('100')
  await page.getByRole('button', { name: 'Distribuir saldo nas parcelas', exact: true }).click()
  await page.getByRole('button', { name: 'Salvar contrato', exact: true }).click(); await page.locator('dialog').waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Ver parcelas', exact: true }).click()
  snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.loans.length, 1); assert.equal(snapshot.bills.filter(b => b.loanId).length, 3)
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '04-financiamento.png') })
  await page.getByRole('button', { name: 'Patrimônio', exact: true }).click()
  await page.getByRole('button', { name: 'Adicionar patrimônio', exact: true }).click()
  await page.getByLabel('Nome do bem', { exact: true }).fill('Meu carro')
  await page.getByLabel('Categoria do patrimônio', { exact: true }).fill('Veículo')
  await page.getByLabel('Data de aquisição', { exact: true }).fill('2026-01-01')
  await page.getByLabel('Preço de aquisição do bem inteiro', { exact: true }).fill('40000')
  await page.getByLabel('Valor estimado 1', { exact: true }).fill('50000')
  await page.getByLabel('Financiamento vinculado', { exact: true }).selectOption({ label: 'Financiamento do carro' })
  await page.getByRole('button', { name: 'Ícone Carro', exact: true }).click()
  await page.getByRole('button', { name: 'Salvar patrimônio', exact: true }).click(); await page.locator('dialog').waitFor({ state: 'hidden' })
  await page.locator('.property-card').filter({ hasText: 'Meu carro' }).waitFor()
  assert.equal(await page.locator('.patrimony-hero .motion-number').getAttribute('data-value'), '4280000')
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '05-patrimonio.png') })
  await page.reload(); await page.locator('.property-card').waitFor()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1000, 720))
  await page.screenshot({ animations: 'disabled', path: join(artifacts, '06-patrimonio-compacto.png') })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
  await page.getByRole('button', { name: 'Contas a pagar', exact: true }).click()
  await page.locator('.bills-list').waitFor(); await page.screenshot({ animations: 'disabled', path: join(artifacts, '07-contas-compacto.png') })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
  snapshot = await page.evaluate(() => window.electronAPI.getSnapshot())
  assert.equal(snapshot.assets[0].icon, 'car'); assert.equal(snapshot.attachments.length, 1)
  assert.deepEqual(errors, [])
  writeFileSync(join(artifacts, 'result.json'), JSON.stringify({ status: 'passed', errors, tests: ['discreet-workspace-menu', 'variable-recurring-bill', 'confirm-amount', 'partial-custom-payment', 'unclassified-adjustment', 'undo-and-quick-pay', 'pdf-attachment', 'calendar', 'loan-schedule', 'property-net-worth', 'reload-persistence', '1000px-layout'], artifacts }, null, 2))
  console.log(JSON.stringify({ status: 'passed', artifacts }))
} catch (error) { if (page) await page.screenshot({ animations: 'disabled', path: join(artifacts, 'failure.png') }).catch(() => {}); console.error(error); process.exitCode = 1 }
finally { await app?.close(); rmSync(temporary, { recursive: true, force: true }) }
